config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("musics.urls")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("notjustmusic.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("musics/", include("musics.urls", namespace="musics")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

musics/urls.py
from django.urls import path
from django.conf.urls import url
from .views import AuthorList, AlbumList, MusicList, AlbumMusicList, MusicCreate, FavoriteMusic, favourite_song, AuthorAlbumList

app_name = 'musics'

urlpatterns = [
    path("", AlbumList.as_view(), name="album_list"),
    path("authors/", AuthorList.as_view(), name="author_list"),
    path("musics/", MusicList.as_view(), name="music_list"),
    path("musics/<int:pk>/", AlbumMusicList.as_view(), name="album_music_list"),
    path("new/", MusicCreate.as_view(), name="music_form"),
    path("favorite_list/", FavoriteMusic.as_view(), name="favorite_list"),
    path("like/<int:pk>/", favourite_song, name="like_song"),
    path("author_album/<int:pk>/", AuthorAlbumList.as_view(), name="authors_albums")
]

notjustmusic/users/urls.py
from django.urls import path

from .views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

musics/models.py
from django.db import models
from django.urls import reverse
from notjustmusic.users.models import User


class Author(models.Model):
    name = models.CharField(max_length=100, verbose_name="название")
    picture = models.ImageField(upload_to="media/", verbose_name="аватар")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "исполнитель"
        verbose_name_plural = "исполнители"


class Albums(models.Model):
    name = models.CharField(max_length=100, verbose_name="название")
    data = models.DateField(verbose_name="дата издания")
    picture = models.ImageField(upload_to="media/", verbose_name="обложка")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="исполнитель", default=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "альбом"
        verbose_name_plural = "альбомы"


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="название")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Music(models.Model):
    position = models.CharField(max_length=3, verbose_name="position_in_album", default=1)
    name = models.CharField(max_length=100, verbose_name="название")
    music = models.FileField(upload_to="media/", verbose_name="песня")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="исполнитель", default=1)
    album = models.ForeignKey(Albums, on_delete=models.CASCADE, verbose_name="альбом", default=1)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="категория", default='punk')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "трек"
        verbose_name_plural = "треки"


# class FavoriteMusicList(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     music = models.ForeignKey(Music, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.user
#
#     class Meta:
#         verbose_name = ""
#         verbose_name_plural = ""


class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorite_music = models.ManyToManyField(Music)

    def __str__(self):
        user = str(self.user)
        return user

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

notjustmusic/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for NotJustMusic."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

notjustmusic/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

musics/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from .models import Music, Category, Albums, Author, Users
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.


class MusicList(ListView):
    model = Music
    template_name = "musics/music_list.html"
    context_object_name = "musics"

    def get_queryset(self):
        return Music.objects.all()


class AlbumMusicList(ListView):
    model = Music
    template_name = "musics/album_music_list.html"
    context_object_name = "musics"

    def get_queryset(self):
        self.album = get_object_or_404(Albums, pk=self.kwargs['pk'])
        return Music.objects.filter(album=self.album)


class MusicCategory(ListView):
    model = Category
    template_name = "templates/musics/"
    context_object_name = "categories"


class AlbumList(ListView):
    model = Albums
    template_name = "musics/album_list.html"
    context_object_name = "albums"

    def get_queryset(self):
        return Albums.objects.all()


class AuthorList(ListView):
    model = Author
    template_name = "musics/author_list.html"
    context_object_name = "authors"

    def get_queryset(self):
        return Author.objects.all()


class AuthorAlbumList(ListView):
    model = Albums
    template_name = "musics/authors_albums.html"
    context_object_name = "authors_albums"

    def get_queryset(self):
        self.author = get_object_or_404(Author, pk=self.kwargs['pk'])
        return Albums.objects.filter(author=self.author)


class MusicCreate(LoginRequiredMixin, CreateView):
    model = Music
    fields = ["name", "music", "author", "album", "category", "position"]
    success_url = reverse_lazy("musics:music_list")


class MusicDetail(DetailView):
    model = Music
    template_name = "musics/music_detail.html"
    context_object_name = "music"


@login_required
def favourite_song(request, pk):
    song = get_object_or_404(Music, pk=pk)
    user, created = Users.objects.get_or_create(user=request.user)
    music = Music.objects.get(name=song)
    if not user.favorite_music.filter(music=song).exists():
        user.favorite_music.add(music)
        user.save()
        print(str(user.favorite_music))
        print(str(song))
        return redirect('musics:favorite_list')
    else:
        messages.info(request, 'Этот трек уже в ваших избранных!')
        return redirect('musics:favorite_list')


class FavoriteMusic(ListView):
    model = Users
    template_name = "musics/favorite_songs.html"
    context_object_name = "favorite_list"

    def get_queryset(self):
        return Users.objects.get(user=self.request.user)

notjustmusic/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

notjustmusic/templates/musics/album_list.html
{% extends "base.html" %}
{% block content %}
<body>
<div class="row row-cols-1 row-cols-md-3 g-4">
   {% for album in albums %}
  <div class="col" style="padding-bottom: 1rem;">
    <div class="card" style="width: 18rem; height: 28rem; padding-bottom: 1rem;">
      <a href="{% url 'musics:album_music_list' pk=album.pk %}"><img src="{{ album.picture.url }}" class="card-img-top" alt="..."></a>
      <div class="card-body">
        <a href="{% url 'musics:album_music_list' pk=album.pk %}"><h5 class="card-title">{{ album.name }}</h5></a>
        <p class="card-text">{{ album.author }}</p>
        <p class="card-text">{{ album.data }}</p>
      </div>
    </div>
  </div>
    {% endfor %}
</div>
</body>
{% endblock %}

notjustmusic/templates/musics/album_music_list.html
{% extends "base.html" %}
{% block content %}
<body>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Play</th>
      <th scope="col">Author</th>
      <th scope="col"></th>
    </tr>
  </thead>
    {% for music in musics %}
  <tbody>
    <tr>
      <td>{{ music.position }}</td>
      <td>{{ music.name }}</td>
      <td>
        <audio controls preload="auto">
              <source src="{{ music.music.url }}" type="audio/mpeg">
        </audio></td>
      <td>{{ music.author }}</td>
      <td><a href="{% url 'musics:like_song' pk=music.pk %}"><i class="fa fa-heart-o" style="font-size:24px"></i></a></td>
    </tr>
  </tbody>
    {% endfor %}
  </table>
</div>
</body>
{% endblock %}

notjustmusic/templates/musics/author_list.html
{% extends "base.html" %}
{% block content %}
<body>
<div class="row row-cols-1 row-cols-md-2 g-4">
   {% for author in authors %}
  <div class="col">
      <div class="card" style="width: 18rem; height: 25rem">
        <img src="{{ author.picture.url }}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{ author.name }}</h5>
        </div>
      </div>
  </div>
    {% endfor %}
</div>
</body>
{% endblock %}

notjustmusic/templates/musics/authors_albums.html
{% extends "base.html" %}
{% block content %}
<body>
<div class="row row-cols-1 row-cols-md-3 g-4">
   {% for album in albums %}
  <div class="col" style="padding-bottom: 1rem;">
    <div class="card" style="width: 18rem; height: 28rem; padding-bottom: 1rem;">
      <a href="{% url 'musics:album_music_list' pk=album.pk %}"><img src="{{ album.picture.url }}" class="card-img-top" alt="..."></a>
      <div class="card-body">
        <a href="{% url 'musics:album_music_list' pk=album.pk %}"><h5 class="card-title">{{ album.name }}</h5></a>
        <p class="card-text">{{ album.author }}</p>
        <p class="card-text">{{ album.data }}</p>
      </div>
    </div>
  </div>
    {% endfor %}
</div>
</body>
{% endblock %}

notjustmusic/templates/musics/favorite_songs.html
{% extends "base.html" %}
{% block content %}
<body>
<div class="row row-cols-1 row-cols-md-3 g-4">
   {% for music in favorite_list %}
  <div class="col">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ music.favorite_music }}</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{ favorite_list }}</li>
          <li class="list-group-item">{{ music.album }}</li>
          <li class="list-group-item">{{ music.author }}</li>
          <li class="list-group-item">{{ music.category }}</li>
          <li class="list-group-item">
            <audio controls preload="auto">
              <source src="{{ music.music.url }}" type="audio/mpeg">
            </audio>
          </li>
        </ul>
      </div>
  </div>
    {% endfor %}
</div>
</body>
{% endblock %}

notjustmusic/templates/musics/music_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data" >{% csrf_token %}

  {{ form|crispy }}

      <div class="control-group" style="max-width: 200px">
      <div class="controls">
        <button type="submit" class="btn">Сохранить</button>
      </div>
    </div>

</form>
{% endblock %}

notjustmusic/templates/musics/music_list.html
{% extends "base.html" %}
{% block content %}
<body>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Play</th>
      <th scope="col">Author</th>
      <th scope="col"></th>
    </tr>
  </thead>
    {% for music in musics %}
  <tbody>
    <tr>
      <td>{{ music.name }}</td>
      <td>
        <audio controls preload="auto">
              <source src="{{ music.music.url }}" type="audio/mpeg">
        </audio></td>
      <td>{{ music.author }}</td>
      <td><a href="{% url 'musics:like_song' pk=music.pk %}"><i class="fa fa-heart-o" style="font-size:24px"></i></a></td>
    </tr>
  </tbody>
    {% endfor %}
  </table>
</div>
</body>
{% endblock %}